services:
   gsm_repro:
      container_name: gsm_repro
      build:
         context: ./
         dockerfile: gsm_repro.Dockerfile
      ports:
         - "8888:8888"
      volumes:
         - type: bind
           source: ../
           target: /home/app